#!/usr/bin/env bash
# This script displays a list of all currently running processes
# It must show all processes, for all users, including those which might not have a TTY
# Should display a user-oriented format
# Must show process hierarchy

ps -a -x -u -f
